server:
  port: 8081

spring:
  datasource:
    #    zeroDateTimeBehavior 地址可以是空的
    url: jdbc:mysql://localhost:3306/blok?serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: "0000"
    driver-class-name: com.mysql.jdbc.Driver
files:
  upload:
    # 文件上传允许的类型
    allowTypes:
      - image/jpeg
      - image/png
      - image/jpg
      - image/gif